vert-x3/vertx-micrometer-metrics

src/test/java/io/vertx/micrometer/VertxPoolMetricsTest.java
From time to time CI tests fail due to timing uncertainty. So relaxing the rule.
=> Relax pool metrics test double comparator

pom.xml, src/main/asciidoc/dataobjects.adoc, src/main/asciidoc/index.adoc, src/main/java/examples/MetricsExamples.java, src/main/java/io/vertx/micrometer/MicrometerMetricsOptions.java, src/main/java/io/vertx/micrometer/backends/BackendRegistries.java, src/main/java/io/vertx/micrometer/backends/BackendRegistry.java, src/test/java/io/vertx/micrometer/backend/CustomMicrometerMetricsITest.java, src/test/java/io/vertx/micrometer/backend/InfluxDbReporterITest.java, src/test/java/io/vertx/micrometer/backend/InfluxDbTestHelper.java
MicrometerMetricsOptions now can take any existing MicrometerRegistry. In such case it won't go over the creation process of a backend-dedicated registry. It's also useful to allow Micrometer CompositeRegistry
=> Add ability to provide any MicrometerRegistry in options

src/main/java/io/vertx/micrometer/impl/VertxHttpClientMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxHttpServerMetrics.java, src/test/java/io/vertx/micrometer/VertxHttpClientServerMetricsTest.java
Add Label.Method for following Vertx HTTP server metrics. The PR fixes https://github.com/vert-x3/vertx-micrometer-metrics/issues/41. 
- requests
- requestResetCount
- responseTime
=> [#41] Provide HTTP Method key in all the relevant VertxHttpServerMetrics 

src/main/java/io/vertx/micrometer/impl/VertxHttpClientMetrics.java, src/test/java/io/vertx/micrometer/VertxHttpClientServerMetricsTest.java
The counters for "responseCount" are retrieved but never incremented.
I dont know if this should also be backported to the 3.5 branch.
=> Increment responseCount counter

src/main/asciidoc/dataobjects.adoc, src/main/asciidoc/index.adoc, src/main/generated/io/vertx/micrometer/VertxPrometheusOptionsConverter.java, src/main/java/examples/MicrometerMetricsExamples.java, src/main/java/io/vertx/micrometer/VertxPrometheusOptions.java, src/main/java/io/vertx/micrometer/backends/PrometheusBackendRegistry.java, src/test/java/io/vertx/micrometer/backend/PrometheusMetricsITest.java
Fixes #22 , fixes #52 
- new boolean flag publishQuantiles in VertxPrometheusOptions. If not enabled, summary and timer metrics (such as response times) will not include bucket stats to allow histogram-quantiles querying
- update examples and documentation
Add more examples in documentation
=> Add option flag to publish quantiles for Prometheus

src/main/java/io/vertx/micrometer/backends/BackendRegistries.java
Having a check of `instanceof` before `#getPrometheusOptions` causes
code using other backend registry throw no class defined exception:
```
java.lang.NoClassDefFoundError: io/micrometer/prometheus/PrometheusMeterRegistry
```
Reversing this condition fixes the issue due to both short-circuiting and lazy class loading.
Generally `instanceof` branch can be removed at all as 2nd PrometheusBackendRegistry constructor
does nothing else than setting generic prometheus options that could be done in:
https://github.com/vert-x3/vertx-micrometer-metrics/blob/74d70d238d1c160318bbf5f558c39e64af74b679/src/main/java/io/vertx/micrometer/backends/PrometheusBackendRegistry.java#L51
Original issue reference: https://github.com/vert-x3/vertx-micrometer-metrics/issues/79
=> reverse condiditional check for configuring Prometheus backend

src/test/java/io/vertx/micrometer/VertxEventBusMetricsTest.java, src/test/java/io/vertx/micrometer/VertxHttpClientServerMetricsTest.java
The event bus failing test looks like a regression: eventbus error not being reported anymore to the metrics SPI ?
=> Fix broken tests

src/main/java/io/vertx/micrometer/backends/BackendRegistries.java, src/test/java/io/vertx/micrometer/MatchersTest.java
Need to reverse logic and use "deny" instead of "accept" ; "accept" only is useful to shortcut next filters processing but will not be useful to filter out metrics (unless they're explicitly said to be all denied by default)
Added a test
Fixes https://github.com/vert-x3/vertx-micrometer-metrics/issues/92
=> Fix acceptance matchers ineffective

src/main/asciidoc/index.adoc, src/main/java/io/vertx/micrometer/impl/VertxEventBusMetrics.java, src/test/java/io/vertx/micrometer/VertxEventBusMetricsTest.java, src/test/java/io/vertx/micrometer/backend/PrometheusMetricsITest.java
This is a follow-up on f369f39c20c120103a65701e9f689d197c97465d / https://github.com/eclipse-vertx/vert.x/issues/3270
A few notes:
- SPI was refactored by merging 'beginHandleMessage' and 'endHandleMessage' hooks, so measuring time became pointless
- processingTime was anyway not really relevant as it was missing any asynchronous-spent time
- Errors (=exceptions) are not provided anymore to metrics SPI
- Errors != replyFailures: the latter is still reported
Documentation also updated to reflect these changes
=> Change EB processingTime to processed counter, remove errors counter (breaking changes)

src/main/java/io/vertx/micrometer/impl/VertxEventBusMetrics.java, src/test/java/io/vertx/micrometer/RegistryInspector.java, src/test/java/io/vertx/micrometer/VertxEventBusMetricsTest.java
Mirroring behaviour in HandlerRegistration
Fixes https://github.com/vert-x3/vertx-micrometer-metrics/issues/95
=> Reset pending gauge on handler unregistered

src/main/asciidoc/index.adoc, src/main/java/io/vertx/micrometer/impl/VertxHttpClientMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxPoolMetrics.java, src/test/java/io/vertx/micrometer/VertxHttpClientServerMetricsTest.java, src/test/java/io/vertx/micrometer/service/MetricsServiceImplTest.java
2 new metrics:
- Queue size gauge
- Queue delay timer
Both of them labeled after local & remote addresses
Fixes https://github.com/vert-x3/vertx-micrometer-metrics/issues/88
=> Add queue metrics on http client

src/main/asciidoc/dataobjects.adoc, src/main/asciidoc/enums.adoc, src/main/asciidoc/index.adoc, src/main/generated/io/vertx/micrometer/MicrometerMetricsOptionsConverter.java, src/main/java/io/vertx/micrometer/Label.java, src/main/java/io/vertx/micrometer/MetricsDomain.java, src/main/java/io/vertx/micrometer/MicrometerMetricsOptions.java, src/main/java/io/vertx/micrometer/impl/AbstractMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxClientMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxMetricsImpl.java, src/main/java/io/vertx/micrometer/impl/VertxNetClientMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxNetServerMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxPoolMetrics.java, src/test/java/io/vertx/micrometer/RegistryInspector.java, src/test/java/io/vertx/micrometer/VertxClientMetricsTest.java, src/test/java/io/vertx/micrometer/VertxDatagramSocketMetricsTest.java
Creates 5 new metrics per type of client:
- vertx.xxx.queue.time (histogram)
- vertx.xxx.queue.pending (gauge)
- vertx.xxx.processing.time (histogram)
- vertx.xxx.processing.pending (gauge)
- vertx.xxx.reset (counter)
They're all labeled by remote address and namespace. The provided "type" (e.g. "sql") is used as metric prefix (e.g. "vertx.sql.").
There's some refactoring on categories / MetricDomains, as this was before a closed list (enum), now it's an opened list that accepts custom values (e.g. "sql"). Hence it's still possible to turn off just one "ClientMetrics" instance based on its type, via the metrics options.
Fixes https://github.com/vert-x3/vertx-micrometer-metrics/issues/106
=> Implement ClientMetrics interface

pom.xml
Note that 1.5.x is an LTS release line of Micrometer. It's better to have it for vert.x 4.
Unit tests seem OK. I'll run some end-to-end tests.
=> Bump micrometer 1.5.2

src/main/asciidoc/index.adoc, src/main/java/io/vertx/micrometer/impl/VertxHttpClientMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxHttpServerMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxNetClientMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxNetServerMetrics.java, src/test/java/io/vertx/micrometer/UnixSocketTest.java, src/test/java/io/vertx/micrometer/VertxHttpClientServerMetricsTest.java, src/test/java/io/vertx/micrometer/VertxNetClientServerMetricsTest.java, src/test/java/io/vertx/micrometer/service/MetricsServiceImplTest.java
Having a summary for bytes read/write doesn't make sense anymore (see https://github.com/eclipse-vertx/vert.x/pull/3586)
Change them to counter.
As a follow-up we can create metrics for req/resp sizes, just for HTTP.
Related to https://github.com/eclipse-vertx/vert.x/issues/3585
@vietj this should fix the test failures
=> Fix net client/server metrics

src/main/asciidoc/index.adoc, src/main/java/examples/MicrometerMetricsExamples.java, src/main/java/io/vertx/micrometer/MicrometerMetricsOptions.java, src/main/java/io/vertx/micrometer/impl/VertxHttpServerMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxMetricsImpl.java, src/main/java/io/vertx/micrometer/impl/meters/Counters.java, src/main/java/io/vertx/micrometer/impl/meters/Gauges.java, src/main/java/io/vertx/micrometer/impl/meters/Summaries.java, src/main/java/io/vertx/micrometer/impl/meters/Timers.java, src/test/java/io/vertx/micrometer/VertxHttpServerMetricsConfigTest.java, src/test/java/io/vertx/micrometer/impl/meters/CountersTest.java, src/test/java/io/vertx/micrometer/impl/meters/GaugesTest.java, src/test/java/io/vertx/micrometer/impl/meters/SummariesTest.java, src/test/java/io/vertx/micrometer/impl/meters/TimersTest.java, src/test/java/io/vertx/micrometer/service/MetricsServiceImplTest.java
- Allows to implement a CustomTagsProvider interface to provide tags out
of HttpRequest objects.
- Add tests
Fixes https://github.com/vert-x3/vertx-micrometer-metrics/issues/89
=> Implement custom tags provider for HTTP metrics

src/main/asciidoc/index.adoc
fix typo
`vertx_http_client_ active_requests` to `vertx_http_client_active_requests`
Motivation:
Found a typo when I tried to translate document to Chinese
=> Documentation typo for HTTP Client active requests

src/main/asciidoc/index.adoc, src/main/java/examples/MicrometerMetricsExamples.java, src/main/java/io/vertx/micrometer/MicrometerMetricsOptions.java, src/main/java/io/vertx/micrometer/impl/VertxMetricsImpl.java, src/test/java/io/vertx/micrometer/VertxHttpClientServerMetricsTest.java, src/test/java/io/vertx/micrometer/VertxHttpServerMetricsConfigTest.java
Also:
- update doc
- keep but deprecate old option get/setter
It's a follow-up on https://github.com/vert-x3/vertx-micrometer-metrics/pull/135
=> Rename request tags provider option for consistency

pom.xml
Motivation:
Maintenance/ Keep dependencies up to date
=> Bump micrometer from 1.6.2  to 1.8.4

src/main/java/io/vertx/micrometer/impl/AbstractMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxClientMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxDatagramSocketMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxEventBusMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxHttpClientMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxHttpServerMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxMetricsFactoryImpl.java, src/main/java/io/vertx/micrometer/impl/VertxMetricsImpl.java, src/main/java/io/vertx/micrometer/impl/VertxNetClientMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxNetServerMetrics.java, src/main/java/io/vertx/micrometer/impl/VertxPoolMetrics.java, src/main/java/io/vertx/micrometer/impl/meters/Gauges.java, src/test/java/io/vertx/micrometer/impl/meters/GaugesTest.java
Fixes #91
Micrometer does not let us access the object that is referenced in a gauge. For this reason, we have to put such objects in a map which keys are the gauge id.
(Note: we have to do this because our gauges are computed dynamically with the provided tags.)
So far, to avoid race conditions, the access to gauges has been serialized. But that comes with an important performance impact.
The solution proposed here consists in using:
- a non-blocking construct instead of synchronization
- having a single gaugesTable for all Gauges object instance (multiple Gauges instances can try to create the same gauge concurrently)
Also, sometimes multiples Vert.x instances can be created in the same JVM. A good practice is to provide a name to the registry using MetricsOptions, but if the user does …
=> Do not serialize access to gauge objects

src/test/java/io/vertx/micrometer/MatchersTest.java, src/test/java/io/vertx/micrometer/MicrometerMetricsTestBase.java, src/test/java/io/vertx/micrometer/UnixSocketTest.java, src/test/java/io/vertx/micrometer/VertxClientMetricsTest.java, src/test/java/io/vertx/micrometer/VertxDatagramSocketMetricsTest.java, src/test/java/io/vertx/micrometer/VertxEventBusMetricsTest.java, src/test/java/io/vertx/micrometer/VertxHttpClientServerMetricsTest.java, src/test/java/io/vertx/micrometer/VertxHttpServerMetricsConfigTest.java, src/test/java/io/vertx/micrometer/VertxNetClientServerMetricsTest.java, src/test/java/io/vertx/micrometer/VertxPoolMetricsTest.java, src/test/java/io/vertx/micrometer/backend/CustomMicrometerMetricsITest.java, src/test/java/io/vertx/micrometer/backend/InfluxDbReporterITest.java, src/test/java/io/vertx/micrometer/backend/JmxMetricsITest.java, src/test/java/io/vertx/micrometer/backend/PrometheusMetricsITest.java, src/test/java/io/vertx/micrometer/service/MetricsServiceImplTest.java
Fixes #139 
Using different registries avoids having clashes in meter names that can results in intermittent failures.
=> Make sure all tests use a different registry

src/main/java/io/vertx/micrometer/impl/meters/Gauges.java, src/test/java/io/vertx/micrometer/EmptyCompositeMeterRegistryTest.java
=> Gauge lookup infinite loop when CompositeRegistry is still empty

src/main/java/io/vertx/micrometer/impl/meters/Gauges.java, src/test/java/io/vertx/micrometer/impl/meters/GaugesTest.java
Fixes #150
This new implementation allows to support Noop gauges (when the user configures the registry to deny some meters) and gets rid of the loop.
=> Infinite loop when Gauge builder returns a noop-gauge

src/main/java/io/vertx/micrometer/Label.java, src/main/java/io/vertx/micrometer/backends/BackendRegistries.java, src/main/java/io/vertx/micrometer/impl/Labels.java, src/main/java/io/vertx/micrometer/impl/meters/Counters.java, src/main/java/io/vertx/micrometer/impl/meters/Gauges.java, src/main/java/io/vertx/micrometer/impl/meters/Summaries.java, src/main/java/io/vertx/micrometer/impl/meters/TagsCache.java, src/main/java/io/vertx/micrometer/impl/meters/Timers.java, src/test/java/io/vertx/micrometer/impl/LabelsTest.java, src/test/java/io/vertx/micrometer/impl/meters/TagsDataTest.java
The SPI implementation makes a lot of redundant copies and allocations when resolving tags/gauges or mapping meter ids.
See individual commit messages for details about the problems and the changes.
This PR has been tested with https://github.com/tsegismont/vertx-mysql-client-gc-nepotism, running the app for about 5 mins and capturing data with JFR.
The results in Mission Control memory section: (for reference, 53.2MB of MySQL ColumnDefinition allocated over this period)
- `ArrayList$Itr` instances down to 1.81MB, was 111MB
- `ImmutableTag` instances are no longer visible, was 83MB
- `Tag[]` instances are no longer visible, was 74.6MB
- `Tags` instances are no longer visible, was 43.3MB
- `ValueSupplier` instances are no longer visible in Mission Control, was 26.8MB
- java streams related …
=> Reduce allocations

src/main/asciidoc/index.adoc
This metrics should be named `vertx_http_server_active_ws_connections` and not `vertx_http_client_active_ws_connections`. See https://github.com/vert-x3/vertx-micrometer-metrics/blob/master/src/main/java/io/vertx/micrometer/impl/VertxHttpServerMetrics.java#L64
=> Fix a typo in the `http_server` metrics documentation

src/main/java/io/vertx/micrometer/impl/meters/TagsCache.java, src/test/java/io/vertx/micrometer/impl/meters/TagsCacheTest.java
See #185
Use flyweight and cache only when running on standard context in event loop. Otherwise, the cache might return wrong tags (e.g. when invoked inside executeBlocking on standard context).
=> Fix TagsCache concurrency bug

src/main/java/io/vertx/micrometer/impl/AbstractMetrics.java, src/main/java/io/vertx/micrometer/impl/MeterCache.java, src/main/java/io/vertx/micrometer/impl/VertxMetricsFactoryImpl.java, src/main/java/io/vertx/micrometer/impl/VertxMetricsImpl.java
Related to https://github.com/eclipse-vertx/vert.x/issues/5078
FastThreadLocal can cause a memory-leak if not used as a class constant.
=> Avoid FastThreadLocal in MeterCache

src/main/asciidoc/index.adoc, src/main/java/examples/MicrometerMetricsExamples.java, src/main/java/io/vertx/micrometer/MicrometerMetricsFactory.java, src/main/java/io/vertx/micrometer/MicrometerMetricsOptions.java, src/main/java/io/vertx/micrometer/backends/BackendRegistries.java, src/main/java/io/vertx/micrometer/impl/VertxMetricsImpl.java, src/main/resources/META-INF/services/io.vertx.core.spi.VertxServiceProvider, src/test/java/io/vertx/micrometer/EmptyCompositeMeterRegistryTest.java, src/test/java/io/vertx/micrometer/MicrometerMetricsTestBase.java, src/test/java/io/vertx/micrometer/backend/CustomMicrometerMetricsITest.java, src/test/java/io/vertx/micrometer/service/MetricsServiceImplTest.java
Instead expose the metrics factory as part of public API and set it on the factory.
=> Deprecate setting a MeterRegistry on MicrometerMetricsOptions

src/main/java/io/vertx/micrometer/impl/meters/LongGaugeBuilder.java
See #232
This costs a volatile write, even when the supplier is not actually used (because the meter was previously registered).
But it's the only way to make sure the registered meter always has a properly initialized value supplier.
=> LongGaugeBuilder: always set the meterId field of the supplier

src/test/java/io/vertx/micrometer/VertxEventBusMetricsTest.java, src/test/java/io/vertx/micrometer/VertxHttpClientServerMetricsTest.java, src/test/java/io/vertx/micrometer/VertxHttpServerMetricsConfigTest.java, src/test/java/io/vertx/micrometer/VertxNetClientServerMetricsTest.java
This is an attempt to fix intermittent build failures.
In some cases (only on CI), some tests fail because a previous test could not close properly a net or http server (java.net.BindException: Address already in use).
When this happens, the CI logs also print a message indicating a failure to properly close a server:
```
2024-09-05T05:02:17.7401756Z Sep 05, 2024 5:02:17 AM io.netty.util.concurrent.DefaultPromise safeExecute
2024-09-05T05:02:17.7410618Z SEVERE: Failed to submit a listener notification task. Event loop shut down?
2024-09-05T05:02:17.7412174Z java.util.concurrent.RejectedExecutionException: event executor terminated
2024-09-05T05:02:17.7413826Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:931)
2024-09-05T05:02:17.7415853Z 	at …
```
=> Clean test verticle deployments

pom.xml
Release notes: https://github.com/micrometer-metrics/micrometer/releases/tag/v1.13.6
>  ⭐ New Features / Enhancements
> Improve memory usage of StepBucketHistogram https://github.com/micrometer-metrics/micrometer/issues/4954
> 🐞 Bug Fixes
> Instrumented Java 11 HttpClient does not re-throw exceptions in sendAsync call https://github.com/micrometer-metrics/micrometer/issues/5136
> Map time units to UCUM format for Dynatrace https://github.com/micrometer-metrics/micrometer/issues/5588
> Aspects' tagsBasedOnJoinPoint may throw uncaught exception https://github.com/micrometer-metrics/micrometer/issues/5584
> Set user agent header in OTLP registry https://github.com/micrometer-metrics/micrometer/issues/5577
> MicrometerHttpRequestExecutor fails to instrument with Apache HC 5.4 …
=> Upgrade micrometer to 1.13.6

pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.14.3
> - Handle RuntimeException when getting/setting JMS headers https://github.com/micrometer-metrics/micrometer/pull/5746
> - NPE occurs when AOP is applied to a method that returns CompletableFuture https://github.com/micrometer-metrics/micrometer/issues/5741
> - Performance regression in MeterRegistry#remove with many meters https://github.com/micrometer-metrics/micrometer/issues/5466
> - Exponential histogram throws ArrayIndexOutOfBoundsException https://github.com/micrometer-metrics/micrometer/issues/5740
=> Upgrade Micrometer to 1.14.3

src/main/java/io/vertx/micrometer/backends/PrometheusBackendRegistry.java, src/test/java/io/vertx/micrometer/backend/PrometheusEmbeddedLauncherITest.java
Fixes #251
When the embedded server is enabled, the backend registry creates an internal Vert.x instance, for the sole purpose of serving metrics data over HTTP.
In general, it's not a problem because the default Vert.x options don't enable metrics. But if metrics are enabled with the vertx.metrics.options.enabled system property, the internal Vert.x instance will have metrics enabled too (because of code introduced to retrofit Vert.x builder in Vert.x 4). And then the application fail to start with a StackOverflow error (because the default PrometheusBackendRegistry is reused and reinitialized).
So, we can avoid that situation by making sure the internal Vert.x instance uses dummy metrics.
This problem doesn't apply to Vert.x 5.
=> StackOverflowError when using PrometheusOptions
