- src/main/java/io/vertx/micrometer/impl/VertxEventBusMetrics.java
- src/test/java/io/vertx/micrometer/VertxHttpClientServerMetricsTest.java
> Ignore internal eventbus metrics

- src/main/java/examples/MicrometerMetricsExamples.java
- src/main/java/io/vertx/micrometer/PrometheusScrapingHandler.java
- src/main/java/io/vertx/micrometer/impl/PrometheusScrapingHandlerImpl.java
> Polyglot Vert.x Web route handler for Prometheus scraping

- src/main/asciidoc/dataobjects.adoc
- src/main/generated/io/vertx/micrometer/MicrometerMetricsOptionsConverter.java
- src/main/java/io/vertx/micrometer/MicrometerMetricsOptions.java
- src/main/java/io/vertx/micrometer/VertxInfluxDbOptions.java
- src/main/java/io/vertx/micrometer/VertxJmxMetricsOptions.java
- src/main/java/io/vertx/micrometer/VertxPrometheusOptions.java
- src/main/java/io/vertx/micrometer/impl/VertxMetricsFactoryImpl.java
- src/test/java/io/vertx/micrometer/ExternalConfigurationTest.java
- src/test/java/io/vertx/micrometer/MyVerticle.java
> Add a switch for JVM metrics in MicrometerMetricsOptions

- src/main/asciidoc/index.adoc
- src/main/generated/io/vertx/micrometer/MicrometerMetricsOptionsConverter.java
- src/main/java/examples/MicrometerMetricsExamples.java
cc @cescoffier => related to https://github.com/vert-x3/vertx-micrometer-metrics/issues/52
> Add documentation for percentiles

- src/test/java/io/vertx/micrometer/VertxEventBusMetricsTest.java
Should hopefully fix #56 (bad timing on test)
> EB test failure: wait for expected value

- src/main/java/io/vertx/micrometer/impl/VertxMetricsImpl.java
Closes #19
Follows up on eclipse/vert.x#2352
> Remove timer metrics

- src/main/asciidoc/index.adoc
- src/main/java/examples/MicrometerMetricsExamples.java
- src/main/java/io/vertx/micrometer/backends/BackendRegistries.java
- src/main/java/io/vertx/micrometer/backends/PrometheusBackendRegistry.java
- src/test/java/io/vertx/micrometer/backend/CustomMicrometerMetricsITest.java
Also add test, example & documentation
> Fix reused registry ignoring Prometheus options

- src/main/java/io/vertx/micrometer/backends/BackendRegistries.java
- src/main/java/io/vertx/micrometer/impl/Labels.java
- src/test/java/io/vertx/micrometer/backend/PrometheusMetricsITest.java
https://github.com/vert-x3/vertx-micrometer-metrics/issues/75
> fix(NPE): Add null check for tag values

- src/main/java/io/vertx/micrometer/impl/VertxEventBusMetrics.java
> Protect from NPE when handler is unexpectedly null

- src/main/java/io/vertx/micrometer/impl/MetricsServiceImpl.java
- src/test/java/io/vertx/micrometer/service/MetricsServiceImplTest.java
Implemented the conversion to json of missing metrics (long task timer, time gauge, function counter, function timer).
> Fix metric to json conversion

- src/main/java/io/vertx/micrometer/MicrometerMetricsOptions.java
Fixes https://github.com/vert-x3/vertx-micrometer-metrics/issues/96
> Make MicrometerMetricsOptions override setFactory

- src/main/asciidoc/index.adoc
- src/main/java/io/vertx/micrometer/impl/VertxEventBusMetrics.java
- src/test/java/io/vertx/micrometer/VertxEventBusMetricsTest.java
Updated test with new metrics & behaviour
> Implement new discarded message hook

- src/main/asciidoc/enums.adoc
- src/main/asciidoc/index.adoc
- src/main/java/io/vertx/micrometer/Label.java
- src/main/java/io/vertx/micrometer/MicrometerMetricsOptions.java
- src/main/java/io/vertx/micrometer/impl/VertxHttpServerMetrics.java
- src/test/java/io/vertx/micrometer/VertxHttpClientServerMetricsTest.java
fixes #34 
Companion PRs:
* required: https://github.com/eclipse-vertx/vert.x/pull/3532
* https://github.com/vert-x3/vertx-web/pull/1682
* https://github.com/vert-x3/vertx-dropwizard-metrics/pull/101
> Implement route support for http request metrics (#34)

- pom.xml
- src/main/java/io/vertx/micrometer/impl/Labels.java
- src/main/java/io/vertx/micrometer/impl/VertxDatagramSocketMetrics.java
- src/main/java/io/vertx/micrometer/impl/VertxHttpServerMetrics.java
- src/main/java/io/vertx/micrometer/impl/VertxNetClientMetrics.java
- src/main/java/io/vertx/micrometer/impl/VertxNetServerMetrics.java
- src/test/java/io/vertx/micrometer/UnixSocketTest.java
Fixes https://github.com/vert-x3/vertx-micrometer-metrics/issues/112
cc @Stimzz
> Fix crash with unix sockets

- pom.xml
Signed-off-by: Paulo Lopes <pmlopes@gmail.com>
> Micrometer upgrade to 1.6.2

- src/main/java/io/vertx/micrometer/impl/VertxHttpServerMetrics.java
Signed-off-by: Jörg Eichhorn <joerg.eichhorn@kiwigrid.com>
Motivation:
See Julien's comments on https://github.com/vert-x3/vertx-dropwizard-metrics/pull/101
> Reduce garbage.

- src/main/java/io/vertx/micrometer/MicrometerMetricsOptions.java
- src/main/java/io/vertx/micrometer/impl/VertxHttpClientMetrics.java
- src/main/java/io/vertx/micrometer/impl/VertxMetricsImpl.java
- src/test/java/io/vertx/micrometer/VertxHttpClientServerMetricsTest.java
New PR after rebasing with latest master
Related to https://github.com/vert-x3/vertx-micrometer-metrics/issues/133
> Implement custom tags provider for HTTP Client metrics(rebased)

- src/main/java/io/vertx/micrometer/impl/AbstractMetrics.java
- src/main/java/io/vertx/micrometer/impl/VertxClientMetrics.java
- src/main/java/io/vertx/micrometer/impl/VertxDatagramSocketMetrics.java
- src/main/java/io/vertx/micrometer/impl/VertxEventBusMetrics.java
- src/main/java/io/vertx/micrometer/impl/VertxHttpClientMetrics.java
- src/main/java/io/vertx/micrometer/impl/VertxHttpServerMetrics.java
- src/main/java/io/vertx/micrometer/impl/VertxMetricsFactoryImpl.java
- src/main/java/io/vertx/micrometer/impl/VertxMetricsImpl.java
- src/main/java/io/vertx/micrometer/impl/VertxNetClientMetrics.java
- src/main/java/io/vertx/micrometer/impl/VertxNetServerMetrics.java
- src/main/java/io/vertx/micrometer/impl/VertxPoolMetrics.java
- src/main/java/io/vertx/micrometer/impl/meters/Gauges.java
- src/test/java/io/vertx/micrometer/impl/meters/GaugesTest.java
Backport of #143 to `4.2` branch
> Do not serialize access to gauge objects

- src/main/java/io/vertx/micrometer/impl/meters/Gauges.java
- src/test/java/io/vertx/micrometer/EmptyCompositeMeterRegistryTest.java
> Gauge lookup infinite loop when CompositeRegistry is still empty

- pom.xml
Release notes https://github.com/micrometer-metrics/micrometer/releases/tag/v1.9.4
> build(deps): bump micrometer from 1.9.3 to 1.9.4

- pom.xml
See https://github.com/micrometer-metrics/micrometer/releases/tag/v1.9.5
> build(deps): bump micrometer from 1.9.4 to 1.9.5

- pom.xml
> Upgrade to Micrometer 1.10.3

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.10.4
> Upgrade to Micrometer 1.10.4

- pom.xml
- src/main/generated/io/vertx/micrometer/MicrometerMetricsOptionsConverter.java
- src/main/generated/io/vertx/micrometer/VertxInfluxDbOptionsConverter.java
- src/main/generated/io/vertx/micrometer/VertxJmxMetricsOptionsConverter.java
- src/main/generated/io/vertx/micrometer/VertxPrometheusOptionsConverter.java
- src/main/java/io/vertx/micrometer/Label.java
- src/main/java/io/vertx/micrometer/backends/BackendRegistries.java
- src/main/java/io/vertx/micrometer/impl/Labels.java
- src/main/java/io/vertx/micrometer/impl/meters/Gauges.java
- src/test/java/io/vertx/micrometer/EmptyCompositeMeterRegistryTest.java
- src/test/java/io/vertx/micrometer/UnixSocketTest.java
- src/test/java/io/vertx/micrometer/impl/LabelsTest.java
- src/test/java/io/vertx/micrometer/impl/meters/GaugesTest.java
> Backport Gauge lookup enhancements

- src/main/java/io/vertx/micrometer/package-info.java
See https://github.com/vert-x3/issues/issues/612
Easy one, no callbacks in this module
> Deprecate callbacks

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.10.5
> Upgrade to Micrometer 1.10.5

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.10.7
> Upgrade to Micrometer 1.10.7

- pom.xml
Backports https://github.com/vert-x3/vertx-micrometer-metrics/pull/186
> build(deps): bump micrometer to 1.11.2

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.11.3
>  Upgrade to Micrometer 1.11.3

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.11.4
> Upgrade to Micrometer 1.11.4

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.11.4
>  Upgrade to Micrometer 1.11.4

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.11.5
> Upgrade to Micrometer 1.11.5

- src/main/java/io/vertx/micrometer/impl/VertxMetricsImpl.java
- src/test/java/io/vertx/micrometer/ExternalConfigurationTest.java
> Add more JVM metrics

- src/main/asciidoc/index.adoc
- src/main/generated/io/vertx/micrometer/MicrometerMetricsOptionsConverter.java
- src/main/java/examples/MicrometerMetricsExamples.java
- src/main/java/io/vertx/micrometer/MicrometerMetricsOptions.java
- src/main/java/io/vertx/micrometer/impl/VertxMetricsImpl.java
- src/test/java/io/vertx/micrometer/ExternalConfigurationTest.java
> Enable Netty metrics through configuration

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.12.1
> Upgrade to Micrometer 1.12.1

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.12.2
> Upgrade to Micrometer 1.12.2

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.12.3
> Upgrade to Micrometer 1.12.3

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.12.3
> Uprade to Micrometer 1.12.3

- pom.xml
fixes metrics for gc times and pauses for ZGC generational https://github.com/micrometer-metrics/micrometer/issues/4764
> upgrade to micrometer 1.12.4

- src/main/asciidoc/index.adoc
- src/main/java/examples/MicrometerMetricsExamples.java
- src/main/java/io/vertx/micrometer/MicrometerMetricsFactory.java
- src/main/java/io/vertx/micrometer/MicrometerMetricsOptions.java
- src/main/java/io/vertx/micrometer/backends/BackendRegistries.java
- src/main/java/io/vertx/micrometer/impl/VertxMetricsImpl.java
- src/main/resources/META-INF/services/io.vertx.core.spi.VertxServiceProvider
- src/test/java/io/vertx/micrometer/EmptyCompositeMeterRegistryTest.java
- src/test/java/io/vertx/micrometer/MicrometerMetricsTestBase.java
- src/test/java/io/vertx/micrometer/backend/CustomMicrometerMetricsITest.java
- src/test/java/io/vertx/micrometer/service/MetricsServiceImplTest.java
Instead expose the metrics factory as part of public API and set it on the factory.
> Remove setting a MeterRegistry on the MicrometerMetricsOptions

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.13.3
> Upgrade micrometer to 1.13.3

- src/main/java/io/vertx/micrometer/impl/meters/Gauges.java
Fixes #232
This costs a volatile write, even when the supplier is not actually used (because the meter was previously registered).
But it's the only way to make sure the registered meter always has a properly initialized value supplier.
> LongGaugeBuilder: always set the meterId field of the supplier

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.13.4
> Upgrade to Micrometer 1.13.4

- src/main/java/io/vertx/micrometer/impl/HttpUtils.java
- src/main/java/io/vertx/micrometer/impl/VertxHttpClientMetrics.java
- src/main/java/io/vertx/micrometer/impl/VertxHttpServerMetrics.java
- src/test/java/io/vertx/micrometer/tests/VertxHttpClientServerMetricsTest.java
- src/test/java/io/vertx/micrometer/tests/VertxHttpServerMetricsTest.java
> HTTP PATH metrics don't consistently report a path

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.12.12
> Upgrade to Micrometer 1.12.12

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.13.7
> Upgrade to Micrometer 1.13.7

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.14.0
> Upgrade to Micrometer 1.14.0

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.14.1
> Upgrade to Micrometer 1.14.1

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.14.2
> Upgrade Micrometer from 1.14.1 to 1.14.2

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.14.4
> Upgrade to Micrometer 1.14.4

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.14.6
> Bump micrometer to 1.14.6

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.14.7
> Bump micrometer to 1.14.7

- pom.xml
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.15.0
> Bump micrometer to 1.15.0

- src/main/java/module-info.java
> [JPMS] Backend registries should only be required for compilation
